/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.lowest.base.utils;

import android.content.Context;
import android.app.ActivityManager;
import java.util.List;
import java.util.Iterator;
import android.content.ComponentName;
import android.content.Intent;
import android.content.pm.PackageManager;

public class MCActivityUtils {
    
    public static boolean isAction(Context context) {
        ActivityManager am = (ActivityManager)context.getApplicationContext().getSystemService(Context.ACTIVITY_SERVICE);
        List<ActivityManager.RunningTaskInfo> tasks = am.getRunningTasks(0x1);
        if((tasks != null) && (!tasks.isEmpty())) {
            ComponentName topActivity = tasks.get(0x0).topActivity;
            return (topActivity.getPackageName().equals(context.getApplicationContext().getPackageName()));
        }
        return false;
    }
    
    public static void getTopActivity(Context context) {
        ActivityManager manager = (ActivityManager)context.getSystemService(Context.ACTIVITY_SERVICE);
        List<ActivityManager.RunningTaskInfo> runningTaskInfos = manager.getRunningTasks(0x64);
        if(!runningTaskInfos.iterator().hasNext()) {
        }
        ActivityManager.RunningTaskInfo info = (ActivityManager.RunningTaskInfo)runningTaskInfos.iterator().next();
        MCLogUtil.e("ActivityUtils", new StringBuilder().append(info.topActivity).append("============info.id===========").append(info.id).append(info.topActivity).append("============info.id===========").append(info.id).append("=============info.baseActivity===").append(info.baseActivity).toString());
    }
    
    public static int getActivitySize(Context context) {
        return 1;
    }
    
    public static void launchApp(Context context) {
        try {
            Intent intent = new Intent();
            PackageManager packageManager = context.getPackageManager();
            intent = packageManager.getLaunchIntentForPackage(context.getPackageName());
            intent.setFlags(0x14200000);
            context.startActivity(intent);
            return;
        } catch(Exception localException1) {
        }
    }
}
