/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.lowest.base.utils;

import android.content.Context;
import android.graphics.drawable.Drawable;
import android.content.pm.ApplicationInfo;
import android.content.pm.PackageManager;
import android.os.Bundle;
import android.app.ActivityManager;
import java.util.List;
import java.util.Iterator;
import android.content.pm.PackageInfo;
import android.content.pm.Signature;
import java.security.cert.CertificateException;
import java.security.cert.CertificateFactory;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.security.cert.Certificate;
import java.security.cert.X509Certificate;
import java.security.PublicKey;
import java.math.BigInteger;

public class MCAppUtil {
    
    public static String getAppName(Context context) {
        return context.getApplicationInfo().loadLabel(context.getPackageManager()).toString();
    }
    
    public static String getVersionName(Context context) {
        try {
            return context.getPackageManager().getPackageInfo(context.getPackageName(), PackageManager.GET_URI_PERMISSION_PATTERNS).versionName;
        } catch(PackageManager.NameNotFoundException e) {
            e.printStackTrace();
        }
        return "";
    }
    
    public static int getVersionCode(Context context) {
        try {
            return context.getPackageManager().getPackageInfo(context.getPackageName(), PackageManager.GET_URI_PERMISSION_PATTERNS).versionCode;
        } catch(PackageManager.NameNotFoundException e) {
            e.printStackTrace();
        }
        return 0x0;
    }
    
    public static String getPackageName(Context context) {
        return context.getPackageName();
    }
    
    public static Drawable getAppIcon(Context context) {
        return context.getApplicationInfo().loadIcon(context.getPackageManager());
    }
    
    public static int getPid(Context context, String processName) {
        ActivityManager mActivityManager = (ActivityManager)context.getSystemService(Context.ACTIVITY_SERVICE);
        List<ActivityManager.RunningAppProcessInfo> appProcessList = mActivityManager.getRunningAppProcesses();
        if(!appProcessList.iterator().hasNext()) {
        }
        ActivityManager.RunningAppProcessInfo appProcess = (ActivityManager.RunningAppProcessInfo)appProcessList.iterator().next();
        if(processName.equals(appProcess.processName)) {
            return appProcess.pid;
        }
        return 0x0;
    }
    
    public static String getSingInfo(Context context) {
        try {
            PackageInfo packageInfo = context.getPackageManager().getPackageInfo(context.getPackageName(), PackageManager.GET_SIGNATURES);
            Signature[] signatures = packageInfo.signatures;
            Signature signature = signatures[0x0];
            parseSignature(signature.toByteArray());
        } catch(PackageManager.NameNotFoundException e) {
            e.printStackTrace();
        }
        return null;
    }
    
    public static String parseSignature(byte[] signature) {
        try {
            CertificateFactory certFactory = CertificateFactory.getInstance("X.509");
            X509Certificate cert = (X509Certificate)certFactory.generateCertificate(new ByteArrayInputStream(signature));
            String pubKey = cert.getPublicKey().toString();
            return cert.getSerialNumber().toString();
        } catch(CertificateException e) {
            e.printStackTrace();
        }
        return null;
    }
    
    public static String getMetaValue(Context context, String metaKey) {
        return "";
    }
}
