/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.lowest.base.utils;

import android.content.Context;
import android.content.pm.PackageManager;
import android.content.pm.PackageInfo;
import android.content.pm.ApplicationInfo;
import java.io.File;
import android.content.Intent;
import android.net.Uri;
import java.util.List;

public class MCApkUtil {
    
    public static void installApk(Context context, String apkSDPath) {
        File file = new File(apkSDPath);
        Intent intent = new Intent();
        intent.addFlags(0x10000000);
        intent.setAction("android.intent.action.VIEW");
        intent.setDataAndType(Uri.fromFile(file), "application/vnd.android.package-archive");
        context.startActivity(intent);
    }
    
    public static void launchApk(Context context, String packageName) {
        Intent intent = context.getPackageManager().getLaunchIntentForPackage(packageName);
        if(intent != null) {
            context.startActivity(intent);
        }
    }
    
    public static String getPackageName(Context context, String path) {
        PackageManager pm = context.getPackageManager();
        PackageInfo info = pm.getPackageArchiveInfo(path, PackageManager.GET_ACTIVITIES);
        if(info != null) {
            ApplicationInfo appInfo = info.applicationInfo;
            return appInfo.packageName;
        }
        return null;
    }
    
    public static boolean isInstallApk(String packageName, Context context) {
        PackageManager packageManager = context.getPackageManager();
        List<PackageInfo> packageInfoList = packageManager.getInstalledPackages(0x0);
        int i = 0;
        if(i >= packageInfoList.size()) {
            i = i + 0x1;
            return false;
        }
        PackageInfo packageInfo = (PackageInfo)packageInfoList.get(i);
        if(packageName.equals(packageInfo.packageName)) {
            return true;
        }
        return false;
    }
}
