/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.lowest.base.utils;

import android.content.Context;
import java.io.InputStreamReader;
import android.content.res.Resources;
import android.content.res.AssetManager;
import java.io.InputStream;
import java.io.BufferedReader;
import java.io.Reader;

public class MCAssetsUtils {
    
    public static String getFromAssets(Context context, String filename) {
        try {
            BufferedReader paramString = new BufferedReader(new InputStreamReader(context.getResources().getAssets().open(filename)));
            String str;
            String total;
            for (total = "";; total = total + str)
            {
                str = paramString.readLine();
                if (str == null) {
                    return total;
                }
            }
        } catch (Exception e) {
            return "";
        }
    }
}
