/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.lowest.base.utils;

import android.util.Log;
import android.os.Build;

public class MCLogUtil {
    public static int VERBOSE = 0x1;
    public static int DEBUG = 0x2;
    public static int INFO = 0x3;
    public static int WARN = 0x4;
    public static int ERROR = 0x5;
    private static int level = DEBUG;
    public static boolean isLog = false;
    
    public static void i(String tag, String msg) {
        if((isPrintLog()) && (level <= INFO)) {
            Log.i(tag, msg);
        }
    }
    
    public static void d(String tag, String msg) {
        if((isPrintLog()) && (level <= DEBUG)) {
            Log.d(tag, msg);
        }
    }
    
    public static void w(String tag, String msg) {
        if((isPrintLog()) && (level <= WARN)) {
            Log.w(tag, msg);
        }
    }
    
    public static void e(String tag, String msg) {
        if((isPrintLog()) && (level <= ERROR)) {
            Log.e(tag, msg);
        }
    }
    
    public static void v(String tag, String msg) {
        if((isPrintLog()) && (level <= VERBOSE)) {
            Log.v(tag, msg);
        }
    }
    
    public static boolean isPrintLog() {
        return isLog;
    }
    
    private static String getMsgTag(String tag) {
        if(Build.VERSION.SDK_INT > 0xf) {
            return tag + " >> ";
        }
        return "";
    }
}
