/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.mobcent.lowest.base.utils;

import android.content.res.Resources;
import android.content.Context;
import android.content.res.ColorStateList;
import android.graphics.drawable.Drawable;

public class MCResource {
    private static Object lock = new Object();
    private static MCResource mcResource;
    private String pkg;
    private Resources resources;

    private MCResource(Context context) {
        pkg = context.getPackageName();
        resources = context.getResources();
    }

    public static MCResource getInstance(Context context) {
        synchronized (lock)
        {
            if (mcResource == null) {
                mcResource = new MCResource(context.getApplicationContext());
            }
            return mcResource;
        }
    }

    public int getResourcesId(String type, String name) {
        try {
            return resources.getIdentifier(name, type, pkg);
        } catch(Exception e) {
            e.printStackTrace();
        }
        return 0x0;
    }

    public int getStringId(String name) {
        try {
            return resources.getIdentifier(name, "string", pkg);
        } catch(Exception e) {
            e.printStackTrace();
        }
        return 0x0;
    }

    public String getString(String name) {
        String s = "";
        int id = getStringId(name);
        try {
            return s;
        } catch(Exception e) {
            e.printStackTrace();
            return s;
        }
    }

    public int getColorId(String name) {
        try {
            return resources.getIdentifier(name, "color", pkg);
        } catch(Exception e) {
            e.printStackTrace();
        }
        return 0x0;
    }

    public int getColor(String name) {
        int color = 0x0;
        int id = getColorId(name);
        try {
            return color;
        } catch(Exception e) {
            return color;
        }
    }

    public ColorStateList getColorStateList(String name) {
        try
        {
            return this.resources.getColorStateList(getColorId(name));
        }
        catch (Exception paramString) {}
        return null;
    }

    public int getDimenId(String name) {
        try {
            return resources.getIdentifier(name, "dimen", pkg);
        } catch(Exception e) {
            e.printStackTrace();
        }
        return 0x0;
    }

    public int getStyleId(String name) {
        try {
            return resources.getIdentifier(name, "style", pkg);
        } catch(Exception e) {
            e.printStackTrace();
        }
        return 0x0;
    }

    public int getLayoutId(String name) {
        try {
            return resources.getIdentifier(name, "layout", pkg);
        } catch(Exception e) {
            e.printStackTrace();
        }
        return 0x0;
    }

    public int getViewId(String name) {
        try {
            return resources.getIdentifier(name, "id", pkg);
        } catch(Exception e) {
            e.printStackTrace();
        }
        return 0x0;
    }

    public int getAnimId(String name) {
        try {
            return resources.getIdentifier(name, "anim", pkg);
        } catch(Exception e) {
            e.printStackTrace();
        }
        return 0x0;
    }

    public int getArrayId(String name) {
        try {
            return resources.getIdentifier(name, "array", pkg);
        } catch(Exception e) {
            e.printStackTrace();
        }
        return 0x0;
    }

    public int getDrawableId(String name) {
        try {
            return resources.getIdentifier(name, "drawable", pkg);
        } catch(Exception e) {
            e.printStackTrace();
        }
        return 0x0;
    }

    public Drawable getDrawable(String name) {
        try {
            int id = getDrawableId(name);
            return this.resources.getDrawable(id);
        } catch(Exception e) {
            return null;
        }
    }

    public int getRawId(String name) {
        try {
            return resources.getIdentifier(name, "raw", pkg);
        } catch(Exception e) {
            e.printStackTrace();
        }
        return 0x0;
    }
}
