/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.lowest.base.utils;

import android.content.Context;
import android.widget.Toast;

public class MCToastUtils {
    
    public static void toast(Context context, String msg) {
        toast(context, msg, 0x1);
    }
    
    public static void toast(Context context, String msg, int time) {
        Toast.makeText(context, msg, time).show();
    }
}
