/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.delegate;

import android.view.View;
import android.text.style.ClickableSpan;
import android.text.TextPaint;

public class DZClickSpan extends ClickableSpan {
    private Object data;
    private DZClickSpan.ClickSpanListener<unknown_type> delegate;
    
    public DZClickSpan(DZClickSpan.ClickSpanListener<unknown_type> p1, DZClickSpan.ClickSpanListener p2) {
        // :( Parsing error. Please contact me.
    }
    
    public void onClick(View widget) {
        // :( Parsing error. Please contact me.
    }
    
    public void updateDrawState(TextPaint ds) {
        // :( Parsing error. Please contact me.
    }
}
