/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.delegate;

import android.view.View;
import android.view.MotionEvent;
import android.content.Context;
import android.view.ViewConfiguration;

public abstract class MCOnTouchListener implements View.OnTouchListener {
    private boolean mTouchClick;
    private int mTouchSlop;
    private float startX;
    private float startY;
    
    public abstract void onClick(View p1, MotionEvent p2);
    
    
    public MCOnTouchListener() {
        mTouchClick = false;
    }
    
    public boolean onTouch(View v, MotionEvent event) {
        int action = event.getAction() & 0xff;
        switch(action) {
            case 0:
            {
                mTouchClick = true;
                startX = event.getX();
                startY = event.getY();
                ViewConfiguration configuration = ViewConfiguration.get(v.getContext());
                mTouchSlop = configuration.getScaledTouchSlop();
                break;
            }
            case 1:
            case 3:
            {
                if((mTouchClick) && (Math.abs((event.getX() - startX)) < (float)mTouchSlop) && (Math.abs((event.getY() - startY)) < (float)mTouchSlop)) {
                    onClick(v, event);
                }
                mTouchClick = false;
                break;
            }
            case 2:
            {
                return false;
            }
        }
    }
}
