/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.delegate;


public interface abstract class SubChangeListener {
    
    public abstract void onSelected(boolean p1);
    
}
