/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.fragment;

import android.text.style.URLSpan;
import android.view.View;
import android.content.Intent;
import android.app.Activity;
import com.mobcent.discuz.activity.WebViewFragmentActivity;
import android.content.Context;
import android.widget.TextView;
import android.os.Bundle;
import com.mobcent.lowest.base.utils.MCResource;
import android.text.SpannableString;
import android.content.res.Resources;
import android.text.style.AbsoluteSizeSpan;
import android.text.method.LinkMovementMethod;
import android.text.method.MovementMethod;

public class ErrorFragment extends BaseFragment {
    public static final int CONFIG_ERROR = 0x1;
    private String error;
    private TextView errorText;
    private int type;
    
    public ErrorFragment() {
        error = "";
        type = 0x0;
    }
    public static String TYPE = "type";
    
    protected void initDatas(Bundle savedInstanceState) {
        super.initDatas(savedInstanceState);
        Bundle bundle = getArguments();
        if(bundle != null) {
            error = bundle.getString("error");
            type = bundle.getInt(TYPE);
        }
    }
    
    protected String getRootLayoutName() {
        return "base_error_fragment";
    }
    
    protected void initViews(View rootView) {
        // :( Parsing error. Please contact me.
    }
    
    protected void initActions(View rootView) {
    }
    
    class MyUriSpan extends URLSpan {
        private String url;
        
        public MyUriSpan(ErrorFragment p1, String url) {
            super(url);
            url = url;
        }
        
        public void onClick(View widget) {
            Intent i = new Intent(activity, WebViewFragmentActivity.class);
            i.putExtra("webViewUrl", url);
            startActivity(i);
        }
    }
}
