/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.fragment;

import android.widget.FrameLayout;
import android.support.v4.app.Fragment;
import android.view.View;
import com.mobcent.discuz.android.model.ConfigModuleModel;
import java.util.List;
import com.mobcent.lowest.base.utils.MCListUtils;
import com.mobcent.discuz.android.model.ConfigComponentModel;
import com.mobcent.discuz.base.model.TopSettingModel;
import com.mobcent.discuz.base.dispatch.FragmentDispatchHelper;
import com.mobcent.discuz.base.helper.FragmentOptHelper;
import com.mobcent.discuz.base.delegate.SlideDelegate;
import android.content.Intent;

public class FullPageFragment extends BaseModuleFragment {
    private int ID_WEB_BACK;
    private int ID_WEB_MORE;
    private FrameLayout containerBox;
    private Fragment currentFrgment;
    private View.OnClickListener topClickListener;
    
    public FullPageFragment() {
        currentFrgment = 0x0;
        ID_WEB_BACK = 0x1;
        ID_WEB_MORE = 0x2;
        topClickListener = new View.OnClickListener(this) {
            
            public void onClick(View v) {
                if((v.getTag() != null) && (v.getTag() instanceof TopBtnModel)) {
                    TopBtnModel topBtnModel = (TopBtnModel)v.getTag();
                    if((currentFrgment != null) && (currentFrgment instanceof WebViewFragment)) {
                        WebViewFragment webFragment = currentFrgment;
                        if(topBtnModel.action == ID_WEB_BACK) {
                            webFragment.isChildInteruptBackPress();
                            return;
                        }
                        if(topBtnModel.action == ID_WEB_MORE) {
                            if(DiscuzApplication._instance.isPayed()) {
                                webFragment.topMoreClick();
                            }
                        }
                    }
                }
            }
        };
    }
    
    protected String getRootLayoutName() {
        return "base_full_fragment";
    }
    
    protected void initViews(View rootView) {
        super.initViews(rootView);
        containerBox = (FrameLayout)findViewByName(rootView, "container_layout");
        if(currentFrgment != null) {
            getFragmentHelper().showFragment(currentFrgment);
        }
    }
    
    protected void initActions(View rootView) {
    }
    
    protected void firstCreate() {
        super.firstCreate();
        if((moduleModel != null) && (!MCListUtils.isEmpty(moduleModel.getComponentList()))) {
            List<ConfigComponentModel> componentModels = moduleModel.getComponentList();
            ConfigComponentModel componentModel = 0x0;
            if((componentModels != null) && (!componentModels.isEmpty())) {
                componentModel = componentModels.get(0x0);
                currentFrgment = FragmentDispatchHelper.disPatchFragment(componentModel);
                getFragmentHelper().addFragment(containerBox.getId(), currentFrgment);
            }
        }
    }
    
    public void dealTopBar() {
        if((moduleModel != null) && (!MCListUtils.isEmpty(moduleModel.getComponentList()))) {
            ConfigComponentModel componentModel = (ConfigComponentModel)moduleModel.getComponentList().get(0x0);
            if(componentModel != null) {
                if("userinfo".equals(componentModel.getType())) {
                    TopSettingModel topSettingModel = createTopSettingModel();
                    topSettingModel.isVisibile = false;
                    dealTopBar(topSettingModel);
                }
            }
            return;
        }
        super.dealTopBar();
    }
    
    public boolean isSlideFullScreen() {
        if((currentFrgment != null) && (currentFrgment instanceof SlideDelegate)) {
            return (SlideDelegate)currentFrgment.isSlideFullScreen();
        }
        return false;
    }
    
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if(currentFrgment != null) {
            currentFrgment.onActivityResult(requestCode, resultCode, data);
        }
    }
}
