/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.fragment;

import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.view.View;
import android.os.Bundle;
import android.support.v4.app.FragmentActivity;
import android.content.Context;
import android.widget.ListAdapter;

public class MyListFragment extends BaseFragment {
    private ArrayAdapter<String> arrayAdapter;
    private String[] data;
    private ListView listView;
    
    public MyListFragment() {
        data = new String[] {"a", "b", "c", "d", "e", "f", "g", "h", "i", "b", "c", "d", "e", "f", "g", "h", "i", "b", "c", "d", "e", "f", "g", "h", "i"}
    }
    
    protected void initDatas(Bundle savedInstanceState) {
        super.initDatas(savedInstanceState);
    }
    
    protected String getRootLayoutName() {
        return "base_my_fragment";
    }
    
    protected void initViews(View rootView) {
        listView = (ListView)findViewByName(rootView, "list_layout");
        arrayAdapter = new ArrayAdapter(getActivity(), 0x1090000, 0x1020014, data);
        listView.setAdapter(arrayAdapter);
    }
    
    protected void initActions(View rootView) {
    }
}
