/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.model;

import java.util.List;
import com.mobcent.discuz.android.model.ClassifiedModel;
import com.mobcent.discuz.android.model.TopicDraftModel;
import com.mobcent.discuz.android.model.PermissionModel;

public class PublishTopicModel {
    public int OnlyTopicType;
    public long albumId;
    public String audioPath;
    public long boardId;
    public String boardName;
    public int classificationTopId;
    public int classificationTypeId;
    public List<ClassifiedModel> classifiedModeLoadDatalList<ClassifiedModel>;
    public List<ClassifiedModel> classifiedModelList<ClassifiedModel>;
    public String content;
    public TopicDraftModel draftModel;
    public boolean isQuote;
    public int isShowPostion;
    public boolean isTitle;
    public double latitude;
    public String locationStr;
    public double longitude;
    public String module;
    public PermissionModel permissionModel;
    public String[] picPath;
    public List<String> pollContent;
    public String pollCount;
    public String pollTime;
    public int publishType;
    public int requestLocation;
    public long sortId;
    public String title;
    public long toReplyId;
    public long topicId;
}
