/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.model;


public class TopBtnModel {
    public int action;
    public String icon;
    public int position;
    public Object tag;
    public Object tag2;
    public String title;
}
