/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.model;

import java.util.List;
import com.mobcent.discuz.android.model.ConfigComponentModel;
import com.mobcent.discuz.base.delegate.SubTitleChangeListener;

public class TopSettingModel {
    public boolean isTitleClickAble;
    public boolean isVisibile;
    public List<TopBtnModel> leftModels;
    public List<TopBtnModel> rightModels;
    public int style;
    public List<ConfigComponentModel> subComponentList<ConfigComponentModel>;
    public int subCurrentPosition;
    public SubTitleChangeListener subTitleListener;
    public String title;
    
    public TopSettingModel() {
        isVisibile = true;
        isTitleClickAble = false;
        style = 0x0;
        subCurrentPosition = 0x0;
    }
}
