/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.adapter;

import android.widget.BaseAdapter;
import android.content.Context;
import java.util.List;
import android.os.Handler;
import android.view.LayoutInflater;
import com.mobcent.lowest.base.utils.MCResource;
import android.view.View;
import android.widget.ImageView;

public abstract class BaseSimpleAdapter extends BaseAdapter {
    protected Context context;
    protected List<unknown_type> datas;
    protected Handler handler;
    protected LayoutInflater inflater;
    protected MCResource resource;
    
    public BaseSimpleAdapter(Context context, List<unknown_type> p2) {
        // :( Parsing error. Please contact me.
    }
    
    public List getDatas() {
        // :( Parsing error. Please contact me.
    }
    
    public void setDatas(List<unknown_type> p1) {
        // :( Parsing error. Please contact me.
    }
    
    protected View findViewByName(View parent, String name) {
        // :( Parsing error. Please contact me.
    }
    
    protected void loadImage(ImageView img, String url) {
        // :( Parsing error. Please contact me.
    }
}
