/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.adapter;

import android.widget.BaseAdapter;
import android.content.Context;
import java.util.List;
import android.os.Handler;
import android.view.LayoutInflater;
import com.mobcent.lowest.base.utils.MCResource;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;

public abstract class BaseListAdatper extends BaseAdapter {
    public String TAG;
    protected Context context;
    protected List<unknown_type> datas;
    protected Handler handler;
    protected LayoutInflater inflater;
    protected MCResource resource;
    
    protected abstract String getLayoutName();
    
    
    protected abstract void initViewDatas(Object p1, Object p2, int p3);
    
    
    protected abstract void initViews(View p1, Object p2);
    
    
    protected abstract Object instanceHolder();
    
    
    public BaseListAdatper(Context context, List<unknown_type> p2) {
        // :( Parsing error. Please contact me.
    }
    
    public void getItem(int position) {
        // :( Parsing error. Please contact me.
    }
    
    public int getCount() {
        // :( Parsing error. Please contact me.
    }
    
    public long getItemId(int position) {
        // :( Parsing error. Please contact me.
    }
    
    public View getView(int position, View convertView, ViewGroup parent) {
        // :( Parsing error. Please contact me.
    }
    
    public List getDatas() {
        // :( Parsing error. Please contact me.
    }
    
    public void setDatas(List<unknown_type> p1) {
        // :( Parsing error. Please contact me.
    }
    
    protected View findViewByName(View parent, String name) {
        // :( Parsing error. Please contact me.
    }
    
    protected synchronized void loadImage(View img, String url) {
        // :( Parsing error. Please contact me.
    }
    
    protected void loadImageByTag(ImageView img) {
        // :( Parsing error. Please contact me.
    }
}
