/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.adapter;

import android.widget.BaseAdapter;
import android.content.Context;
import java.util.List;
import com.mobcent.discuz.android.model.TopicModel;
import android.os.Handler;
import android.view.LayoutInflater;
import com.mobcent.lowest.base.utils.MCResource;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.text.TextUtils;
import com.nostra13.universalimageloader.core.ImageLoader;

public abstract class BaseMoreHolderListAdapter extends BaseAdapter {
    protected Context context;
    protected List<TopicModel> datas;
    protected LayoutInflater inflater;
    protected MCResource resource;
    
    protected abstract View getConvertView(View p1, TopicModel p2, ViewGroup p3);
    
    
    protected abstract void initViewDatas(View p1, TopicModel p2, int p3);
    
    public String TAG = "BaseMoreHolderListAdapter";
    protected Handler handler = new Handler();
    
    public BaseMoreHolderListAdapter(Context context, List<TopicModel> datas) {
        context = context;
        datas = datas;
        resource = MCResource.getInstance(context);
        inflater = LayoutInflater.from(context);
    }
    
    public TopicModel getItem(int position) {
        return (TopicModel)datas.get(position);
    }
    
    public int getCount() {
        return datas.size();
    }
    
    public long getItemId(int position) {
        return (long)position;
    }
    
    public View getView(int position, View convertView, ViewGroup parent) {
        convertView = getConvertView(convertView, getItem(position), parent);
        initViewDatas(convertView, getItem(position), position);
        return convertView;
    }
    
    public List getDatas() {
        return datas;
    }
    
    public void setDatas(List<TopicModel> datas) {
        datas = datas;
    }
    
    protected View findViewByName(View parent, String name) {
        return parent.findViewById(resource.getViewId(name));
    }
    
    protected synchronized void loadImage(ImageView img, String url, int width) {
        if(TextUtils.isEmpty(url)) {
            return;
        }
        img.setTag(url);
        ImageLoader.getInstance().displayImage(url, img);
    }
}
