/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.adapter;

import java.util.List;

public class WheelListAdapter implements WheelAdapter {
    private List<String> list;
    
    public WheelListAdapter(List<String> list) {
        list = list;
    }
    
    public int getItemsCount() {
        return list.size();
    }
    
    public String getItem(int index) {
        return (String)list.get(index);
    }
    
    public int getMaximumLength() {
        return list.size();
    }
}
