/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.adapter;


public interface abstract class WheelAdapter {
    
    public abstract String getItem(int p1);
    
    
    public abstract int getItemsCount();
    
    
    public abstract int getMaximumLength();
    
}
