/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.android.constant;


public interface MCShareApiConstant {
    public static final String APP_KEY = "appKey";
    public static final String CONTENT = "content";
    public static final String COUNTRY = "cty";
    public static final String FORUM_KEY = "forumKey";
    public static final String GZIP = "gzip";
    public static final String IDS = "ids";
    public static final String IMEI = "imei";
    public static final String IMSI = "imsi";
    public static final String LAN = "lan";
    public static final String MAC = "mac";
    public static final String MARK = "mark";
    public static final String OPEN_PLAT_TYPE = "openPlatType";
    public static final String PACKAGE_NAME = "packageName";
    public static final String PIC_PATH = "picPath";
    public static final String PLAT_TYPE = "platType";
    public static final int PLAT_TYPE_VALUE = 0x1;
    public static final String SHARE_URL = "shareUrl";
    public static final String SYS_VERSION = "version";
    public static final String UA = "ua";
}
