/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.android.constant;


public interface MCShareReturnConstant {
    public static final String CONNECTION_FAIL = "connection_fail";
    public static final String RS = "rs";
    public static final String RS_FAIL = "Connection fail, pls try again.";
    public static final String RS_REASON = "reason";
    public static final String RS_SUCC = "rs_succ";
}
