/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.android.constant;


public interface MCShareConstant {
    public static final String BASE_URL = "baseUrl";
    public static final String BIND_URL = "bindUrl";
    public static final int CONTENT_TYPE_ANNO = 0x6;
    public static final int CONTENT_TYPE_BAIKE = 0x7;
    public static final int CONTENT_TYPE_FORUM = 0x1;
    public static final int CONTENT_TYPE_GALLERY = 0x2;
    public static final int CONTENT_TYPE_INFO = 0x3;
    public static final int CONTENT_TYPE_VIDEO = 0x5;
    public static final String DOMAIN_URL = "domainUrl";
    public static final String FROM_PHP = "php";
    public static final String IS_BIND = "bind";
    public static final String LIST = "list";
    public static final String PARAM_BASE_URL = "baseUrl";
    public static final String PARAM_BOARD_ID = "boardId";
    public static final String PARAM_CONTENT_TYPE = "contentType";
    public static final String PARAM_FORUM_KEY = "forumKey";
    public static final String PARAM_REPLY_POSTS_ID = "replyPostsId";
    public static final String PARAM_SDK_VERSION = "sdkVersion";
    public static final String PARAM_SHARE_FROM = "shareFrom";
    public static final String PARAM_STYLE = "style";
    public static final String PARAM_TOPIC_ID = "topicId";
    public static final String PHOTO_BASE_PATH = "image_baseUrl";
    public static final String PHOTO_PATH = "photoPath";
    public static final String PHP_CONTENT_TYPE_NEWS = "news";
    public static final String PHP_CONTENT_TYPE_TOPIC = "topic";
    public static final String PIC_PATH = "picPath";
    public static final int SHARE_APP = 0x6;
    public static final String SHARE_CONTENT = "content";
    public static final int SHARE_GAME = 0x7;
    public static final int SHARE_INFO = 0x2;
    public static final int SHARE_MUSIC = 0x4;
    public static final int SHARE_PICTURE = 0x1;
    public static final int SHARE_TOPIC = 0x3;
    public static final String SHARE_URL = "shareUrl";
    public static final int SHARE_VIDEO = 0x5;
    public static final String SITE_ID = "id";
    public static final String SITE_NAME = "name";
    public static final int STYLE_PIC_WORD = 0x1;
}
