/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.widget;

import com.mobcent.discuz.android.model.ClassifyTopModel;
import android.app.Dialog;
import com.mobcent.discuz.android.model.BoardChild;
import android.widget.Button;
import java.util.List;
import android.content.Context;
import android.view.LayoutInflater;
import android.widget.LinearLayout;
import com.mobcent.lowest.base.utils.MCResource;
import android.os.Bundle;
import android.view.View;
import android.widget.TextView;
import android.view.ViewGroup;
import android.text.TextUtils;

public class ClassfiedDialog extends Dialog {
    private BoardChild boardModel;
    private ClassfiedDialog.ClassfiedCallBack callBack;
    private Button cancleBtn;
    private List<ClassifyTopModel> classficationTopList<ClassifyTopModel>;
    private Context context;
    private LayoutInflater inflater;
    private LinearLayout layout;
    private MCResource resource;
    
    public ClassfiedDialog.ClassfiedCallBack getCallBack() {
        return callBack;
    }
    
    public void setCallBack(ClassfiedDialog.ClassfiedCallBack callBack) {
        callBack = callBack;
    }
    
    public ClassfiedDialog(Context context) {
        super(context);
        resource = MCResource.getInstance(context);
        inflater = LayoutInflater.from(context);
        context = context;
    }
    
    public ClassfiedDialog(Context context, int theme, List<ClassifyTopModel> classficationTopList, BoardChild boardModel) {
        super(context, theme);
        resource = MCResource.getInstance(context);
        classficationTopList = classficationTopList;
        inflater = LayoutInflater.from(context);
        context = context;
        boardModel = boardModel;
    }
    
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(resource.getLayoutId("publish_classify_dialog"));
        layout = (LinearLayout)findViewById(resource.getViewId("mc_forun_publish_classify_box"));
        cancleBtn = (Button)findViewById(resource.getViewId("mc_forum_cancle_btn"));
        for(int i = 0x0; i < classficationTopList.size(); i = i + 0x1) {
            ClassifyTopModel topModel = (ClassifyTopModel)classficationTopList.get(i);
            if("sort".equals(topModel.getType())) {
                View itemView = inflater.inflate(resource.getLayoutId("classfication_top_list_item"), 0x0);
                TextView publishText = (TextView)itemView.findViewById(resource.getViewId("mc_forum_publish_text"));
                publishText.setSingleLine(true);
                publishText.setEllipsize(TextUtils.TruncateAt.MIDDLE);
                publishText.setText(topModel.getTitle());
                layout.addView(itemView);
                itemView.setOnClickListener(new View.OnClickListener(this, topModel) {
                    
                    public void onClick(View v) {
                        dismiss();
                        callBack.classfiedTopCallBack(topModel);
                    }
                });
            }
        }
        cancleBtn.setOnClickListener(new View.OnClickListener(this) {
            
            public void onClick(View v) {
                Intent intent = (Activity)context.getIntent();
                intent.putExtra("select_board", boardModel);
                (Activity)context.setResult(0x0, intent);
                (Activity)context.finish();
                dismiss();
            }
        });
    }
    
    public void show() {
        super.show();
    }
    
    public void dismiss() {
        super.dismiss();
    }
}
