/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.widget;

import android.widget.LinearLayout;
import com.mobcent.discuz.android.model.BoardChild;
import com.mobcent.discuz.android.model.ClassifyTopModel;
import java.util.List;
import android.content.Context;
import com.mobcent.discuz.android.model.PermissionModel;
import com.mobcent.lowest.base.utils.MCResource;
import android.util.AttributeSet;
import android.view.ViewGroup;
import com.mobcent.lowest.base.utils.MCPhoneUtil;
import java.util.ArrayList;
import java.util.Map;
import com.mobcent.lowest.base.utils.MCListUtils;
import android.widget.ImageView;
import android.graphics.drawable.Drawable;
import android.widget.TextView;
import android.view.View;
import android.content.res.Resources;
import android.util.DisplayMetrics;
import android.util.TypedValue;
import android.text.TextUtils;

public class MCBoardSortView extends LinearLayout {
    private long boardId;
    private BoardChild boardModel;
    private ClassifyTopModel classficationTopModel;
    private List<ClassifyTopModel> classficationTopModelList<ClassifyTopModel>;
    private Context context;
    private PermissionModel permissionModel;
    private MCResource resource;
    private PermissionModel settingModel;
    
    private MCBoardSortView(Context context) {
        super(context);
    }
    
    private MCBoardSortView(Context context, AttributeSet attrs) {
        super(context, attrs);
    }
    
    public MCBoardSortView(Context context, BoardChild boardModel, PermissionModel settingModel, long boardId) {
        super(context);
        context = context;
        boardModel = boardModel;
        settingModel = settingModel;
        resource = MCResource.getInstance(context);
        setLayoutParams(new LinearLayout.LayoutParams(-0x1, -0x1));
        setOrientation(0x0);
        setPadding(0x0, MCPhoneUtil.getRawSize(context, 0x1, 16.0f), 0x0, 0x0);
        classficationTopModelList = new ArrayList();
        boardId = boardId;
        show();
    }
    
    private void getSettingModel(long boardId) {
        if((settingModel != null) && (settingModel.getPostInfo() != null)) {
            Map<Long, PermissionModel> settingModelHash = settingModel.getPostInfo();
            permissionModel = (PermissionModel)settingModelHash.get(Long.valueOf(boardId));
            if((permissionModel != null) && (!MCListUtils.isEmpty(permissionModel.getTopicPermissionModel().getNewTopicPanel()))) {
                for(int i = 0x0; i < permissionModel.getTopicPermissionModel().getNewTopicPanel().size(); i = i + 0x1) {
                    ClassifyTopModel model = (ClassifyTopModel)permissionModel.getTopicPermissionModel().getNewTopicPanel().get(i);
                    if(model.getType().equals("sort")) {
                        classficationTopModelList.add(model);
                    }
                }
            }
        }
    }
    
    private void show() {
        ImageView imageView = new ImageView(context);
        imageView.setLayoutParams(new LinearLayout.LayoutParams(MCPhoneUtil.getRawSize(context, 0x1, 0.0f), MCPhoneUtil.getRawSize(context, 0x1, 0.0f)));
        if(boardModel.getBoardId() == boardId) {
            imageView.setBackgroundDrawable(resource.getDrawable("mc_forum_personal_set_icon3_h"));
        } else {
            imageView.setBackgroundDrawable(resource.getDrawable("mc_forum_personal_set_icon3_n"));
        }
        addView(imageView);
        TextView textView = new TextView(context);
        textView.setPadding(Math.round(TypedValue.applyDimension(0x1, 10.0f, getResources().getDisplayMetrics())), 0x0, 0x0, 0x0);
        textView.setLayoutParams(new LinearLayout.LayoutParams(-0x2, -0x2));
        textView.setText(boardModel.getBoardName());
        textView.setSingleLine();
        textView.setEllipsize(TextUtils.TruncateAt.END);
        textView.setTextSize(14.0f);
        textView.setTextColor(resource.getColor("mc_forum_text4_desc_normal_color"));
        addView(textView);
        setOnClickListener(new View.OnClickListener(this, imageView) {
            
            public void onClick(View v) {
                imageView.setBackgroundDrawable(resource.getDrawable("mc_forum_personal_set_icon3_h"));
                if((classficationTopModelList != null) && (classficationTopModelList.size() > 0)) {
                    ClassfiedDialog classfiedDialog = new ClassfiedDialog(context, resource.getStyleId("mc_forum_home_publish_classity_dialog"), classficationTopModelList, boardModel);
                    classfiedDialog.show();
                    classfiedDialog.setCallBack(new ClassfiedDialog.ClassfiedCallBack(this) {
                        
                        public void classfiedTopCallBack(ClassifyTopModel topModel) {
                            classficationTopModel = topModel;
                            Intent intent = (Activity)context.getIntent();
                            intent.putExtra("classificationTop_id", classficationTopModel.getActionId());
                            intent.putExtra("select_board", boardModel);
                            (Activity)context.setResult(0x0, intent);
                            (Activity)context.finish();
                        }
                    });
                    return;
                }
                Intent intent = (Activity)context.getIntent();
                intent.putExtra("select_board", boardModel);
                (Activity)context.setResult(0x0, intent);
                (Activity)context.finish();
            }
        });
    }
}
