/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.widget;

import android.widget.EditText;
import android.content.Context;
import android.util.AttributeSet;
import android.view.MotionEvent;
import android.view.ViewParent;

public class MCEditText extends EditText {
    private MCEditText mthis;
    
    public MCEditText(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
        mthis = this;
    }
    
    public MCEditText(Context context, AttributeSet attrs) {
        super(context, attrs);
        mthis = this;
    }
    
    public MCEditText(Context context) {
        super(context);
        mthis = this;
    }
    
    public boolean onTouchEvent(MotionEvent e) {
        if(e.getAction() == 0) {
            if(mthis.getLineCount() > 0x7) {
                getParent().requestDisallowInterceptTouchEvent(true);
            }
        } else if(e.getAction() == 0x2) {
            if(mthis.getLineCount() > 0x7) {
                getParent().requestDisallowInterceptTouchEvent(true);
            }
        } else if(e.getAction() == 0x1) {
            getParent().requestDisallowInterceptTouchEvent(false);
        }
        return super.onTouchEvent(e);
    }
}
