/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.widget;

import android.support.v4.view.ViewPager;
import com.mobcent.lowest.android.ui.widget.PullToRefreshListView;
import android.content.Context;
import android.util.AttributeSet;
import android.view.MotionEvent;

public class MCHeaderViewPager extends ViewPager {
    private ViewPager oSideViewPager;
    private PullToRefreshListView pullToRefreshListView;
    
    public ViewPager getoSideViewPager() {
        return oSideViewPager;
    }
    
    public void setoSideViewPager(MCOutSideViewPager oSideViewPager) {
        oSideViewPager = oSideViewPager;
    }
    
    public void setPullToRefreshListView(PullToRefreshListView pullToRefreshListView) {
        pullToRefreshListView = pullToRefreshListView;
    }
    
    public PullToRefreshListView getPullToRefreshListView() {
        return pullToRefreshListView;
    }
    
    public MCHeaderViewPager(Context context) {
        super(context);
    }
    
    public MCHeaderViewPager(Context context, AttributeSet attrs) {
        super(context, attrs);
    }
    
    public boolean onInterceptTouchEvent(MotionEvent arg0) {
        return super.onInterceptTouchEvent(arg0);
    }
    
    public boolean onTouchEvent(MotionEvent event) {
        return super.onTouchEvent(event);
    }
}
