/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.widget;

import android.content.Context;
import java.util.List;
import com.mobcent.discuz.android.model.TopicModel;
import android.widget.RadioGroup;
import android.os.Handler;
import android.view.LayoutInflater;
import com.mobcent.discuz.module.topic.list.fragment.adapter.ProtalPicList1Adapter;
import android.support.v4.view.ViewPager;
import com.mobcent.lowest.base.utils.MCResource;
import android.view.View;
import android.widget.LinearLayout;
import android.widget.TextView;
import java.util.ArrayList;
import com.mobcent.lowest.android.ui.widget.PullToRefreshListView;
import android.widget.RadioButton;
import android.text.TextUtils;
import android.graphics.drawable.Drawable;
import android.view.ViewGroup;
import com.mobcent.lowest.base.utils.MCPhoneUtil;
import android.support.v4.view.PagerAdapter;

public class MCHeaderPagerHelper {
    private Context context;
    public String TAG = "MCHeaderPagerHelper";
    private final int TIME_DELAYED = 0x1388;
    private MCResource resource = 0x0;
    private LayoutInflater inflater = 0x0;
    private View rootView = 0x0;
    private MCHeaderViewPager pager = 0x0;
    private RadioGroup group = 0x0;
    private TextView titleText = 0x0;
    private LinearLayout titleBox = 0x0;
    private ProtalPicList1Adapter pagerAdapter = 0x0;
    private List<TopicModel> dataList = new ArrayList();
    private int currentPosition = 0x0;
    public int parentPosition = 0x0;
    private final Handler handler = new Handler(this) {
        
        public void handleMessage(Message msg) {
            if(msg.what == 0x1) {
                startAutoScroll();
                switchPager();
            }
        }
    };
    private ViewPager.OnPageChangeListener pagerListener = new ViewPager.OnPageChangeListener(this) {
        
        public void onPageSelected(int position) {
            MCLogUtil.e(TAG, "HeaderView===========parent" + parentPosition + "======" + position);
            currentPosition = position;
            changeTitleText(currentPosition);
        }
        
        public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
        }
        
        public void onPageScrollStateChanged(int state) {
        }
    };
    
    public MCHeaderPagerHelper(Context context) {
        context = context;
        resource = MCResource.getInstance(context);
        inflater = LayoutInflater.from(context);
    }
    
    public View initView(Context context, String style) {
        rootView = inflater.inflate(resource.getLayoutId("portal_recomm_item"), 0x0);
        pager = (MCHeaderViewPager)rootView.findViewById(resource.getViewId("vPager"));
        group = (RadioGroup)rootView.findViewById(resource.getViewId("page_radio"));
        titleText = (TextView)rootView.findViewById(resource.getViewId("title_text"));
        titleBox = (LinearLayout)rootView.findViewById(resource.getViewId("title_layout"));
        int width = 0x0;
        if("card".equals(style)) {
            width = MCPhoneUtil.getDisplayWidth(context) - MCPhoneUtil.getRawSize(context, 0x1, 16.0f);
            pager.setBackgroundResource(resource.getDrawableId("mc_forum_card_bg2"));
        } else {
            width = MCPhoneUtil.getDisplayWidth(context);
            rootView.setPadding(0x0, 0x0, 0x0, 0x0);
        }
        int height = (int)((double)width * 0.5);
        ViewGroup.LayoutParams lp = pager.getLayoutParams();
        lp.height = height;
        lp.width = width;
        pager.setLayoutParams(lp);
        pagerAdapter = new ProtalPicList1Adapter(dataList, style);
        pager.setAdapter(pagerAdapter);
        pager.setOnPageChangeListener(pagerListener);
        return rootView;
    }
    
    public void attachListView(PullToRefreshListView pullToRefreshListView) {
        if(pager != null) {
            pager.setPullToRefreshListView(pullToRefreshListView);
        }
    }
    
    public void notifyDataSetChanged() {
        if(pagerAdapter != null) {
            pagerAdapter.notifyDataSetChanged();
        }
    }
    
    public void setHeaderNoData() {
        if(pagerAdapter != null) {
            pagerAdapter.setDatas(new ArrayList());
        }
        notifyDataSetChanged();
    }
    
    public void setData(List<TopicModel> dataList, String style) {
        if((dataList == null) || (dataList.isEmpty())) {
            setHeaderNoData();
            return;
        }
        dataList.clear();
        dataList.addAll(dataList);
        notifyDataSetChanged();
        if((rootView != null) && (rootView.getVisibility() == 0x8)) {
            rootView.setVisibility(0x0);
        }
        resetRadioAndTitle();
    }
    
    public void resetRadioAndTitle() {
        if(group == null) {
            return;
        }
        group.removeAllViews();
        int count = dataList.size();
        for(int i = 0x0; i < count; i = i + 0x1) {
            RadioButton r = new RadioButton(context);
            r.setId(i);
            r.setButtonDrawable(0x106000d);
            r.setBackgroundResource(resource.getDrawableId("mc_forum_picture_rotate"));
            group.addView(r, new RadioGroup.LayoutParams(MCPhoneUtil.dip2px(context, 9.0f), MCPhoneUtil.dip2px(context, 6.0f)));
            if(i == 0) {
                r.setChecked(true);
                r.requestFocus();
            }
        }
        currentPosition = 0x0;
        group.check(0x0);
        pager.setCurrentItem(currentPosition);
        changeTitleText(currentPosition);
    }
    
    public void changeTitleText(int position) {
        if((group != null) && (dataList.size() > position)) {
            group.check(position);
            (RadioButton)group.getChildAt(position).setChecked(true);
            titleText.setText((TopicModel)dataList.get(position).getTitle());
            if(!TextUtils.isEmpty((TopicModel)dataList.get(position).getTitle())) {
                titleBox.setBackgroundDrawable(resource.getDrawable("mc_forum_card_bg1"));
                return;
            }
            titleBox.setBackgroundDrawable(0x0);
        }
    }
    
    public void startAutoScroll() {
        stopAutoScroll();
        handler.sendEmptyMessageDelayed(0x1, 0x1388);
    }
    
    public void stopAutoScroll() {
        handler.removeMessages(0x1);
    }
    
    public void switchPager() {
        if((pager == null) || (dataList.isEmpty()) || (dataList.size() == 0x1)) {
            stopAutoScroll();
            return;
        }
        changeTitleText(currentPosition);
        if(currentPosition < (dataList.size() - 0x1)) {
            pager.setCurrentItem((currentPosition + 0x1));
            return;
        }
        if(currentPosition == (dataList.size() - 0x1)) {
            pager.setCurrentItem(0x0);
        }
    }
    
    public ViewPager getPager() {
        return pager;
    }
}
