/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.widget;

import android.widget.CheckBox;
import android.content.Context;
import com.mobcent.lowest.base.utils.MCResource;
import android.util.AttributeSet;
import android.widget.LinearLayout;
import com.mobcent.lowest.base.utils.MCPhoneUtil;
import android.view.ViewGroup;

public class MCSetVisibleView extends CheckBox {
    private Context context;
    private MCResource resource;
    private boolean isRapidPublish = false;
    
    public MCSetVisibleView(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
        initData(context);
    }
    
    public MCSetVisibleView(Context context, AttributeSet attrs) {
        super(context, attrs);
        initData(context);
    }
    
    public MCSetVisibleView(Context context) {
        super(context);
        initData(context);
    }
    
    public MCSetVisibleView(Context context, boolean isRapidPublish) {
        super(context);
        initData(context);
        isRapidPublish = isRapidPublish;
    }
    
    private void initData(Context context) {
        context = context;
        resource = MCResource.getInstance(context);
    }
    
    public CheckBox create(String content, int id, boolean isChecked) {
        checkBox.super(context);
        LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(-0x2, MCPhoneUtil.getRawSize(context, 0x1, 41.0f));
        if(isRapidPublish) {
            if(isChecked) {
                checkBox.setButtonDrawable(resource.getDrawableId("mc_forum_publish_icons6_h"));
            } else {
                checkBox.setButtonDrawable(resource.getDrawableId("mc_forum_publish_icons6_n"));
            }
            layoutParams.leftMargin = MCPhoneUtil.getRawSize(context, 0x1, 50.0f);
        } else if(isChecked) {
            checkBox.setButtonDrawable(resource.getDrawableId("mc_forum_detail_select_h"));
        } else {
            checkBox.setButtonDrawable(resource.getDrawableId("mc_forum_detail_select_n"));
        }
        layoutParams.gravity = 0x0;
        checkBox.setLayoutParams(layoutParams);
        checkBox.setTextColor(resource.getColorId("mc_forum_text4_normal_color"));
        checkBox.setTextSize(15.0f);
        checkBox.setId(id);
        checkBox.setText("\t" + content);
        return checkBox;
    }
}
