/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.widget;

import android.app.AlertDialog;
import com.mobcent.discuz.android.model.ClassifiedModel;
import com.mobcent.lowest.base.utils.MCResource;
import android.widget.TextView;
import android.content.Context;
import android.content.DialogInterface;

public class SelectChoseItemBuilder extends AlertDialog.Builder {
    private ClassifiedModel classifiedModel;
    private String[] items;
    private MCResource resource;
    private TextView tv;
    private int selected = -0x1;
    
    public SelectChoseItemBuilder(Context context, String[] items, TextView tv, ClassifiedModel classifiedModel) {
        super(context);
        tv = tv;
        items = items;
        resource = MCResource.getInstance(context);
        classifiedModel = classifiedModel;
    }
    
    public AlertDialog create() {
        setSingleChoiceItems(items, -0x1, new DialogInterface.OnClickListener(this, sb) {
            
            public void onClick(DialogInterface dialog, int which) {
                selected = which;
                sb.append(which + ",");
            }
        });
        setIcon(0x1080027);
        setPositiveButton(resource.getStringId("mc_forum_dialog_confirm"), new DialogInterface.OnClickListener(this) {
            
            public void onClick(DialogInterface dialog, int whichButton) {
                if((classifiedModel != null) && (!classifiedModel.equals(""))) {
                    if(selected > -0x1) {
                        classifiedModel.setClassifiedValue(selected + "");
                        MCLogUtil.i("setPositiveButton", selected + "");
                        tv.setText(items[selected]);
                    }
                }
            }
        });
        setNegativeButton(resource.getStringId("mc_forum_cancel"), new DialogInterface.OnClickListener(this) {
            
            public void onClick(DialogInterface dialog, int whichButton) {
                if((classifiedModel != null) && (!classifiedModel.equals(""))) {
                    classifiedModel.setClassifiedValue("");
                    MCLogUtil.i("setPositiveButton", selected + "");
                    tv.setText("");
                }
            }
        });
        setCancelable(true);
        return super.create();
    }
}
