/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.android.constant;


public interface BaseValueConstant {
    public static final int ALERT_NONE = 0x0;
    public static final int ALERT_TIP = 0x1;
    public static final int IS_HAS_NEXT = 0x1;
}
