/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.android.constant;


public interface BaseApiConstant extends   BaseValueConstant {
    public static final String ACCESS_SECRET = "accessSecret";
    public static final String ACCESS_TOKEN = "accessToken";
    public static final String ALERT = "alert";
    public static final String APPHASH = "apphash";
    public static final String APP_BUILD_VERSION = "458";
    public static final String APP_NAME = "appName";
    public static final String AUTHKEY = "appbyme_key";
    public static final String AUTHORID = "authorId";
    public static final String AVATAR = "avatar";
    public static final String BAIKE_TYPE = "baikeType";
    public static final String BASE_URL = "baseUrl";
    public static final String BODY = "body";
    public static final String CODE = "code";
    public static final String CONFIG_ID = "configId";
    public static final String COUNT = "count";
    public static final String DEVICE = "device";
    public static final String DEVICE_TOKEN = "deviceToken";
    public static final String DIGEST = "digest";
    public static final String DISCUZ_VERSION = "imVersion";
    public static final String DISPLAY_ORDER = "displayorder";
    public static final String DISTANCE = "distance";
    public static final String ERROR_CODE = "errCode";
    public static final String ERROR_INFO = "errInfo";
    public static final String ERROR_NAME = "errorName";
    public static final String EXTERN_INFO = "externInfo";
    public static final String FASTREGISTER = "fastRegister";
    public static final String FORUM_ID = "forumId";
    public static final String FORUM_KEY = "forumKey";
    public static final String FORUM_TYPE = "forumType";
    public static final String GENDER = "gender";
    public static final String HAS_NEXT = "hasNext";
    public static final String HAS_NEXT_PAGE = "has_next";
    public static final String HEAD = "head";
    public static final String HIDDEN = "hidden";
    public static final String ICON_URL = "icon_url";
    public static final String IMEI = "imei";
    public static final String IMSI = "imsi";
    public static final String IS_REQUEST_NO_TOKEN = "isRequestNoToken";
    public static final String IS_VALIDATION = "isValidation";
    public static final String LAST_UPDATE_TIME = "last_update_time";
    public static final String LATITUDE = "latitude";
    public static final String LEVEL_URL = "level_url";
    public static final String LIST = "list";
    public static final String LOCATION = "location";
    public static final String LOCATION_SETTING = "setting";
    public static final String LONGITUDE = "longitude";
    public static final String MOBILE = "mobile";
    public static final String MOULDE_ID = "moduleId";
    public static final String NAME = "name";
    public static final String ORDER = "order";
    public static final String ORDER_BY = "orderBy";
    public static final String PACKAGE_NAME = "packageName";
    public static final String PAGE = "page";
    public static final String PAGE_FROM = "pageFrom";
    public static final String PAGE_SIZE = "pageSize";
    public static final String PLAT_TYPE = "platType";
    public static final String PLAT_TYPE_VALUE = "1";
    public static final String POI = "poi";
    public static final String POIS = "pois";
    public static final String POI_USER = "user";
    public static final String RADIUS = "radius";
    public static final String RATIO = "ratio";
    public static final String REQUIRE_LOCATION = "r";
    public static final String RS = "rs";
    public static final int RS_FAIL = 0x0;
    public static final String SDK_TYPE = "sdkType";
    public static final String SDK_TYPE_VALUE = "";
    public static final String SDK_VERSION = "sdkVersion";
    public static final String SDK_VERSION_VALUE = "2.4.0";
    public static final String SEARCH_KEYWORD = "keyword";
    public static final String SECRET = "secret";
    public static final String SETTING_INTO = "settingInfo";
    public static final String TOKEN = "token";
    public static final String TOTAL_NUM = "total_num";
    public static final String TYPE = "type";
    public static final String TYPE_DEVICE = "1";
    public static final String UID = "uid";
    public static final String USER_ACCESS_SECERT = "secret";
    public static final String USER_ACCESS_TOKEN = "token";
    public static final String USER_ID = "uid";
    public static final String USER_INFO_ID = "userId";
    public static final String USER_NAME = "userName";
    public static final String USER_NEWPASSWORD = "newPassword";
    public static final String USER_OLDPASSWORD = "oldPassword";
}
