/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.android.constant;


public interface ConfigConstant {
    public static final String COMPONENT_ABOUT = "about";
    public static final String COMPONENT_CONFIG_SWITCH = "configSwitch";
    public static final String COMPONENT_DISCOVER = "discover";
    public static final String COMPONENT_FASTAUDIO = "fastaudio";
    public static final String COMPONENT_FASTCAMERA = "fastcamera";
    public static final String COMPONENT_FASTIMAGE = "fastimage";
    public static final String COMPONENT_FASTPOST = "fasttext";
    public static final String COMPONENT_FORUMLIST = "forumlist";
    public static final String COMPONENT_LIVE_LIST = "livelist";
    public static final String COMPONENT_MESSAGELIST = "messagelist";
    public static final String COMPONENT_MODULEREF = "moduleRef";
    public static final String COMPONENT_NEWSLIST = "newslist";
    public static final String COMPONENT_NEWSVIEW = "newsview";
    public static final String COMPONENT_POST_LIST = "postlist";
    public static final String COMPONENT_RECOMMEND_USER_LIST = "recommendUserlist";
    public static final String COMPONENT_SCAN = "scan";
    public static final String COMPONENT_SEARCH = "search";
    public static final String COMPONENT_SETTING = "setting";
    public static final String COMPONENT_SIGN = "sign";
    public static final String COMPONENT_SURROUDING_POST_LIST = "surroudingPostlist";
    public static final String COMPONENT_SURROUDING_USER_LIST = "surroudingUserlist";
    public static final String COMPONENT_TOPICLIST = "topiclist";
    public static final String COMPONENT_TOPICLIST_SIMPLE = "topiclistSimple";
    public static final String COMPONENT_USERINFO = "userinfo";
    public static final String COMPONENT_USER_LIST = "userlist";
    public static final String COMPONENT_WEATHER = "weather";
    public static final String COMPONENT_WEBAPP = "webapp";
    public static final String MODULE_TYPE_CUSTOM = "custom";
    public static final String MODULE_TYPE_FULL = "full";
    public static final String MODULE_TYPE_IMG_TEXT = "news";
    public static final String MODULE_TYPE_ONELINK = "fastpost";
    public static final String MODULE_TYPE_SUBNAV = "subnav";
}
