/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.android.constant;


public interface ReportConstant {
    public static final String ID = "id";
    public static final String IDTYPE = "idType";
}
