/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.android.constant;


public interface UploadConstant {
    public static final String ALBUM_ID = "albumId";
    public static final String FID = "fid";
    public static final String MODULE = "module";
    public static final String MODULE_ALBUM = "album";
    public static final String MODULE_FORUM = "forum";
    public static final String MODULE_PM = "pm";
}
