/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.android.constant;


public interface UriConstant {
    public static final String PARAM_APPBYME_URL = "appbyme_url";
    public static final String PARAM_BOARD_ID = "board_id";
    public static final String PARAM_TOPIC_ID = "topic_id";
    public static final String PARAM_TOPIC_TYPE = "topic_type";
    public static final String PARAM_USRE_ID = "user_id";
    public static final String URI_DETAIL = "detail.appbymeclient.com";
    public static final String URI_USERCENTER = "usercenter.appbymeclient.com";
}
