/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.mobcent.discuz.activity;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup;

import com.appbyme.dev.R;
import com.mobcent.common.JsonConverter;
import com.mobcent.discuz.api.LqForumApi;
import com.mobcent.discuz.base.Tasker;
import com.mobcent.discuz.bean.HomeResult;
import com.mobcent.discuz.fragments.HttpResponseHandler;
import com.mobcent.discuz.ui.ComponentBuilder;


public class ModuleConfigActivity extends BaseRefreshActivity {

    private long mId;
    private ViewGroup viewGroup;

    public static void start(Context context, long id, String title) {
        Intent starter = new Intent(context, ModuleConfigActivity.class);
        starter.putExtra("id",id);
        context.startActivity(starter);
    }

    @Override
    public void initParams(Bundle bundle) {
        mId = bundle.getLong("id");
    }


    @Override
    protected Tasker onExecuteRequest(HttpResponseHandler handler) {
        return LqForumApi.moduleConfig(handler, mId);
    }

    @Override
    protected void showContent(String result) {
        HomeResult home = JsonConverter.format(result, HomeResult.class);
        ComponentBuilder builder = new ComponentBuilder(this);
        builder.setRefreshLayout(mRefreshLayout);
        View comView = builder.buildComponentGroup(home.getComponentList(), true);
        viewGroup.removeAllViews();
        viewGroup.addView(comView);
    }

    @Override
    protected View onCreateContentLayout(ViewGroup container, Bundle savedInstanceState) {
        viewGroup = (ViewGroup) getLayoutInflater().inflate(R.layout.fragment_home, container, false);
        return viewGroup;
    }
}

