/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.lowest.android.ui.module.plaza.constant;


public interface PlazaConstant {
    public static final int ACTION_APP_INSIDE = 0x5;
    public static final int ACTION_BOTTOM_WEBVIEW = 0x2;
    public static final int ACTION_DOWNLOAD = 0x3;
    public static final int ACTION_SYSTEM_BROWER = 0x4;
    public static final int ACTION_TOP_WEBVIEW = 0x1;
    public static final int DEFAULT_PAGE_SIZE = 0x14;
    public static final String INTENT_PLAZA_MODEL = "intentPlazaModel";
    public static final int PLAZA_ID_GAME = 0x1;
    public static final int PLAZA_ID_INVITE = -0x6;
    public static final int PLAZA_ID_SET = -0x5;
    public static final int PLAZA_ID_SOUROUND_POST = -0x2;
    public static final int PLAZA_ID_SOUROUND_RECOMMEND_USER = -0x4;
    public static final int PLAZA_ID_SOUROUND_USER = -0x3;
    public static final int PLAZA_ID_USER_HOME = -0x1;
    public static final float PLAZA_SWITCH_RADIO = 0.4375f;
    public static final String RESOLUTION_100X100 = "100x100";
    public static final String RESOLUTION_200X200 = "200x200";
    public static final String WEB_VIEW_TITLE = "title";
    public static final String WEB_VIEW_TOP = "web_view_is_top";
}
