/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.lowest.android.ui.module.plaza.constant;


public interface PlazaAdPosition {
    public static final int AD_LIST_SPACE = 0x14;
    public static final int SEARCH_FALL_TOP = 0x885;
}
