/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.task;


public interface abstract class BaseRequestCallback {
    
    public abstract void onPostExecute(Object p1);
    
    
    public abstract void onPreExecute();
    
}
