/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.task;

import com.mobcent.discuz.android.service.ConfigService;
import android.content.Context;
import com.mobcent.discuz.android.model.BaseResultModel;
import java.util.List;
import com.mobcent.discuz.android.model.ConfigBoardModel;
import com.mobcent.discuz.android.service.impl.ConfigServiceImpl;

public class ConfigListTask extends BaseTask {
    private ConfigService configService;
    
    public ConfigListTask(Context context, BaseRequestCallback<BaseResultModel<List<ConfigBoardModel>>> _callback) {
        super(context, _callback);
        configService = new ConfigServiceImpl(context);
    }
    
    protected BaseResultModel<List<ConfigBoardModel>> doInBackground(Void params) {
        return configService.queryConfigList();
    }
}
