/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.task;

import com.mobcent.discuz.android.service.UserService;
import android.content.Context;
import com.mobcent.discuz.android.model.BaseResultModel;
import com.mobcent.discuz.android.service.impl.UserServiceImpl;

public class ManageUserAsyncTask extends BaseTask {
    private String type;
    private long userId;
    private UserService userService;
    
    public ManageUserAsyncTask(Context context, BaseRequestCallback<BaseResultModel<Object>> _callback, long userId, String type) {
        super(context, _callback);
        userId = userId;
        type = type;
        userService = new UserServiceImpl(context);
    }
    
    protected BaseResultModel<Object> doInBackground(Void params) {
        return userService.manageUser(userId, type);
    }
}
