/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.task;

import com.mobcent.discuz.android.service.ConfigService;
import android.content.Context;
import com.mobcent.discuz.android.model.BaseResultModel;
import com.mobcent.discuz.android.model.ConfigModuleModel;

public class ModuleTask extends BaseTask {
    private long configId;
    private ConfigService configService;
    private boolean isLocal;
    private long moduleId;
    
    public ModuleTask(Context context, boolean isLocal, long moduleId, long configId, BaseRequestCallback<BaseResultModel<ConfigModuleModel>> p5) {
        // :( Parsing error. Please contact me.
    }
    
    protected BaseResultModel<ConfigModuleModel> doInBackground(Void params) {
        return configService.queryConfigModel(moduleId, configId, isLocal);
    }
}
