/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.task;

import com.mobcent.discuz.android.service.PostsService;
import android.content.Context;
import com.mobcent.discuz.android.model.BaseResultModel;
import java.util.List;
import com.mobcent.discuz.android.model.UploadPictureModel;

public class UploadFileTask extends BaseTask {
    private long albumId;
    private long fid;
    private String[] files;
    private String module;
    private PostsService postsService;
    private long sortId;
    private String type;
    
    public UploadFileTask(Context context, String[] files, String module, String type, long fid, long sortId, long albumId, BaseRequestCallback<BaseResultModel<List<UploadPictureModel>>> p8) {
        // :( Parsing error. Please contact me.
    }
    
    protected BaseResultModel<List<UploadPictureModel>> doInBackground(Void arg0) {
        // :( Parsing error. Please contact me.
    }
}
