/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.task;

import com.mobcent.discuz.android.service.UserService;
import android.content.Context;
import com.mobcent.discuz.android.model.BaseResultModel;
import com.mobcent.discuz.android.model.UserInfoModel;
import com.mobcent.discuz.android.service.impl.UserServiceImpl;

public class UserInfoAsynTask extends BaseTask {
    private long userInfoId;
    private UserService userService;
    
    public UserInfoAsynTask(Context context, BaseRequestCallback<BaseResultModel<UserInfoModel>> _callback, long userInfoId) {
        super(context, _callback);
        userInfoId = userInfoId;
        userService = new UserServiceImpl(context);
    }
    
    protected BaseResultModel<UserInfoModel> doInBackground(Void params) {
        return userService.getUserInfo(userInfoId);
    }
}
