/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.helper;

import com.mobcent.discuz.android.model.TopicDraftModel;
import android.content.Context;
import com.mobcent.discuz.android.service.impl.DraftServiceImpl;
import com.mobcent.discuz.android.service.DraftService;
import com.mobcent.discuz.application.DiscuzApplication;
import android.app.Activity;
import android.app.AlertDialog;
import com.mobcent.lowest.base.utils.MCResource;
import android.content.DialogInterface;
import android.app.Dialog;

public class DraftHelper {
    
    public DraftHelper() {
    }
    
    public static boolean isNeedAlertDialog(Context activity, int type, DraftHelper.DraftDelegate delegate) {
        DraftServiceImpl draftService = new DraftServiceImpl(activity);
        boolean needAlert = draftService.isHasDraftToAlert(type);
        if(needAlert) {
            Activity topActivity = DiscuzApplication._instance.getTopActivity();
            AlertDialog dialog = localint1.setMessage(MCResource.getInstance(activity).getString("mc_forum_draft_reload_alert")).setPositiveButton(MCResource.getInstance(activity).getString("mc_forum_draft_look"), new DialogInterface.OnClickListener(draftService, type, topActivity, activity) {
                
                public void onClick(DialogInterface dialog, int which) {
                    draftService.setLastIgnoreAlert(type);
                    Intent intent = 0x0;
                    if(topActivity != null) {
                        Intent intent = new Intent(topActivity, DraftActivity.class);
                        ActivityDispatchHelper.startActivity(topActivity, intent);
                        return;
                    }
                    Intent intent = new Intent(activity, DraftActivity.class);
                    ActivityDispatchHelper.startActivity(activity, intent);
                }
            }).setNegativeButton(0x1040000, new DraftHelper.1(draftService, type, delegate)).create();
            if(topActivity != null) {
                try {
                    dialog.show();
                    return needAlert;
                } catch(Exception e) {
                    DZDialogHelper.setDialogSystemAlert(dialog);
                    return needAlert;
                }
                DZDialogHelper.setDialogSystemAlert(dialog);
            }
        }
        return needAlert;
    }
}
