/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.helper;

import android.content.Context;
import com.mobcent.lowest.base.utils.MCResource;

public class DZAdPositionHelper {
    
    public static int[] getMainPostPosition(Context context) {
        MCResource resource = MCResource.getInstance(getApplicationContext());
        int adPosition1 = Integer.valueOf(resource.getString("mc_forum_main_posts_position")).intValue();
        int adPosition2 = Integer.valueOf(resource.getString("mc_forum_main_posts_position2")).intValue();
        int adPosition3 = Integer.valueOf(resource.getString("mc_forum_main_posts_position3")).intValue();
        int[] adPositions = new int[0x3];
        adPositions[0x0] = adPosition1;
        adPositions[0x1] = adPosition2;
        adPositions[0x2] = adPosition3;
        return adPositions;
    }
    
    public static int getImgListTopPosition(Context context) {
        MCResource resource = MCResource.getInstance(getApplicationContext());
        return Integer.valueOf(resource.getString("mc_forum_pic_topic_position")).intValue();
    }
    
    public static int getTopicListAdPosition(Context context) {
        MCResource resource = MCResource.getInstance(getApplicationContext());
        return Integer.valueOf(resource.getString("mc_forum_topic_list_content")).intValue();
    }
}
