/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.helper;

import android.app.Dialog;
import android.view.Window;
import android.view.WindowManager;

public class DZDialogHelper {
    
    public static Dialog setDialogSystemAlert(Dialog dialog) {
        WindowManager.LayoutParams lps = getWindow().getAttributes();
        lps.type = 0x7d3;
        getWindow().setAttributes(lps);
        try {
            show();
            return dialog;
        } catch(Exception localException1) {
        }
        return dialog;
    }
}
