/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.helper;

import com.mobcent.lowest.base.utils.MCLogUtil;
import android.text.TextUtils;

public class DZJNIMd5Helper {
    public static String TAG;
    private static DZJNIMd5Helper _instance;
    
    private native String getMd5Result(String p1, String p2);
    
    
    private native String parseMd5(String p1);
    
    
    static {
        TAG = "DZJNIMd5Helper";
        try {
            System.loadLibrary("appbyme");
            return;
        } catch(Exception e) {
            MCLogUtil.e(TAG, e.toString());
        }
    }
    private String md5 = 0x0;
    
    public DZJNIMd5Helper() {
    }
    
    public static synchronized DZJNIMd5Helper getInstance() {
        if(_instance == null) {
            _instance = new DZJNIMd5Helper();
        }
    }
    return _instance;
}

public String getMd5(String plugKey, String forumKey) {
    if(TextUtils.isEmpty(md5)) {
        md5 = getMd5Result(plugKey, forumKey);
    }
    return md5;
}

public String getMd5(String original) {
    return parseMd5(original);
}
}
