/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.helper;

import android.content.Context;
import com.mobcent.lowest.base.utils.MCResource;
import com.mobcent.discuz.base.dispatch.ActivityDispatchHelper;
import android.content.Intent;
import com.mobcent.discuz.activity.WebViewFragmentActivity;

public class DZLinkDoHelper {
    
    public static void linkToPage(Context context, String url, long boardId, String style) {
        MCResource resource = MCResource.getInstance(context);
        if(url.contains(resource.getString("mc_discuz_base_request_url"))) {
            String tid = "";
            if(url.contains("thread-")) {
                tid = split(url, "thread-", "-1-");
                try {
                    ActivityDispatchHelper.startTopicDetailActivity(context, boardId, Long.parseLong(tid), style, -0x1);
                    return;
                } catch(Exception e) {
                    Intent intent = new Intent(context, WebViewFragmentActivity.class);
                    intent.putExtra("webViewUrl", url);
                    startActivity(intent);
                    return;
                }
                if(url.contains("&tid=")) {
                    tid = split(url, "&tid=", "&");
                    String page = split(url, "&page=", "&");
                    try {
                        if(Integer.parseInt(page) <= 0x1) {
                            ActivityDispatchHelper.startTopicDetailActivity(context, boardId, Long.parseLong(tid), style, -0x1);
                            return;
                        }
                    }
                    Intent intent = new Intent(context, WebViewFragmentActivity.class);
                    intent.putExtra("webViewUrl", url);
                    startActivity(intent);
                    return;
                } catch(Exception e) {
                    Intent intent = new Intent(context, WebViewFragmentActivity.class);
                    intent.putExtra("webViewUrl", url);
                    startActivity(intent);
                    return;
                }
                Intent intent = new Intent(context, WebViewFragmentActivity.class);
                intent.putExtra("webViewUrl", url);
                startActivity(intent);
                return;
            }
            Intent intent = new Intent(context, WebViewFragmentActivity.class);
            intent.putExtra("webViewUrl", url);
            startActivity(intent);
        }
    }
    
    public static String split(String url, String form, String end) {
        if(contains(form)) {
            String[] url1 = split(form);
            return url1[0x1].split(end)[0x0];
        }
        return "1";
    }
}
