/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.helper;

import android.content.Context;
import java.util.List;
import com.mobcent.discuz.android.model.ClassifyTypeModel;
import android.content.Intent;
import com.mobcent.discuz.module.publish.fragment.activity.PublishTopicActivity;
import java.io.Serializable;
import com.mobcent.discuz.android.model.TopicDraftModel;
import android.text.TextUtils;
import com.mobcent.discuz.activity.view.MCPopupListView;

public class DZPublishDispathcHelper {
    
    public static void onPublishPopMenuClick(Context context, MCPopupListView.PopupModel popupModel, long boardId, String boardName, List<ClassifyTypeModel> p5) {
        // :( Parsing error. Please contact me.
    }
    
    public static void onPublishPopMenuClick(Context context, String popAction, int classfyId, String classfyName, long boardId, String boardName, List<ClassifyTypeModel> p7) {
        // :( Parsing error. Please contact me.
    }
    
    public static void onPublishCheckDraft(Context context, long boardId, String boardName, List<ClassifyTypeModel> p4) {
        // :( Parsing error. Please contact me.
    }
    
    public static void onPublishNormal(Context context, TopicDraftModel model, long boardId, String boardName, List<ClassifyTypeModel> p5) {
        // :( Parsing error. Please contact me.
    }
    
    public static void onPublishPoll(Context context, long boardId, String boardName, List<ClassifyTypeModel> p4) {
        Intent intent = new Intent(context, PublishTopicActivity.class);
        intent.putExtra("boardId", boardId);
        intent.putExtra("boardName", boardName);
        intent.putExtra("classifyList", p4);
        intent.putExtra("tempParam", 0x3);
        startActivity(intent);
    }
    
    public static void onPublishClassfy(Context context, long boardId, String boardName, int classfyId, String classfyName, List<ClassifyTypeModel> p6) {
        Intent intent = new Intent(context, PublishTopicActivity.class);
        intent.putExtra("boardId", boardId);
        intent.putExtra("boardName", boardName);
        intent.putExtra("classificationTop_id", classfyId);
        intent.putExtra("classificationTop_name", classfyName);
        intent.putExtra("classifyList", p6);
        intent.putExtra("tempParam", 0x2);
        startActivity(intent);
    }
}
