/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.helper;

import com.mobcent.discuz.activity.constant.FinalConstant;
import android.content.Context;
import com.tendcloud.tenddata.TCAgent;
import java.util.HashMap;
import java.util.Map;
import com.mobcent.lowest.base.utils.MCResource;

public class DZTCHelper implements FinalConstant {
    
    public static void onPraiseEvent(Context context) {
        onEvent(context, MCResource.getInstance(context).getString("mc_forum_statistics_praise_event"));
    }
    
    public static void onReplyEvent(Context context) {
        onEvent(context, MCResource.getInstance(context).getString("mc_forum_statistics_reply_event"));
    }
    
    public static void onPublishEvent(Context context, int publishType) {
        switch(publishType) {
            case 4:
            {
                onReplyEvent(context);
                return;
            }
            case 1:
            case 2:
            case 3:
            {
                onEvent(context, MCResource.getInstance(context).getString("mc_forum_statistics_publish_topic_event"));
                break;
            }
        }
    }
    
    public static void onSearchEvent(Context context, String keyWord) {
        String search = MCResource.getInstance(context).getString("mc_forum_statistics_search_event");
        String key = MCResource.getInstance(context).getString("mc_forum_statistics_keyword");
        onEvent(context, search, 0x0, key, keyWord);
    }
    
    private static void onEvent(Context context, String EVENT_ID, String EVENT_LABEL, String key, String value) {
        HashMap<String, Object> kv = new HashMap<String, Object>();
        kv.put(key, value);
        onEvent(context, EVENT_ID, EVENT_LABEL, kv);
    }
    
    private static void onEvent(Context context, String EVENT_ID, String EVENT_LABEL, Map<String, Object> kv) {
        TCAgent.onEvent(context, EVENT_ID, EVENT_LABEL, kv);
    }
    
    private static void onEvent(Context context, String EVENT_ID) {
        TCAgent.onEvent(context, EVENT_ID);
    }
    
    public static void onPageStart(Context context, String pageName) {
        TCAgent.onPageStart(context, pageName);
    }
    
    public static void onPageEnd(Context context, String pageName) {
        TCAgent.onPageEnd(context, pageName);
    }
}
