/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.helper;


public class DZWebWhiteListHelper {
    
    public static boolean isInWhiteList(String url) {
        if(contains("wsh.appbyme.com")) {
            return true;
        }
        return false;
    }
}
