/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.helper;

import android.content.Context;
import com.mobcent.lowest.base.model.JsParamPay;
import com.tencent.mm.sdk.openapi.WXAPIFactory;
import com.tencent.mm.sdk.openapi.IWXAPI;
import com.tencent.mm.sdk.modelpay.PayReq;
import com.tencent.mm.sdk.modelbase.BaseReq;

public class DZWXPayHelper {
    
    public void pay(Context context, JsParamPay payModel) {
        IWXAPI msgApi = WXAPIFactory.createWXAPI(context, 0x0);
        msgApi.registerApp(payModel.appid);
        PayReq req = new PayReq();
        req.appId = payModel.appid;
        req.partnerId = payModel.partnerid;
        req.prepayId = payModel.prepayid;
        req.packageValue = payModel.attach;
        req.nonceStr = payModel.noncestr;
        req.timeStamp = payModel.timestamp;
        req.sign = payModel.sign;
        msgApi.sendReq(req);
    }
}
