/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.helper;

import android.support.v4.app.FragmentManager;
import android.support.v4.app.FragmentTransaction;
import android.support.v4.app.Fragment;

public class FragmentOptHelper {
    public FragmentManager fm;
    private FragmentTransaction ft;
    
    public FragmentOptHelper(FragmentManager fm) {
        fm = fm;
    }
    
    public void addFragment(int boxId, Fragment fragment) {
        if(fragment == null) {
            return;
        }
        try {
            getFt().add(boxId, fragment);
            closeFt();
            return;
        } catch(Exception localException1) {
        }
    }
    
    public void hideFragment(Fragment fragment) {
        if(fragment == null) {
            return;
        }
        try {
            getFt().hide(fragment);
            closeFt();
            return;
        } catch(Exception localException1) {
        }
    }
    
    public void showFragment(Fragment fragment) {
        if(fragment == null) {
            return;
        }
        try {
            getFt().show(fragment);
            closeFt();
            return;
        } catch(Exception localException1) {
        }
    }
    
    public void replaceFragment(int boxId, Fragment fragment) {
        if(fragment == null) {
            return;
        }
        try {
            getFt().replace(boxId, fragment);
            closeFt();
            return;
        } catch(Exception localException1) {
        }
    }
    
    public void removeFragment(Fragment fragment) {
        if(fragment == null) {
            return;
        }
        try {
            getFt().remove(fragment);
            closeFt();
            return;
        } catch(Exception localException1) {
        }
    }
    
    private FragmentTransaction getFt() {
        if(ft == null) {
            ft = fm.beginTransaction();
        }
        return ft;
    }
    
    private void closeFt() {
        if(ft != null) {
            ft.addToBackStack(0x0);
            ft.commit();
            ft = 0x0;
        }
    }
}
