/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.helper;

import com.mobcent.lowest.base.utils.MCLocationUtil;
import android.content.Context;

public class LocationHelper {
    private static MCLocationUtil locationUtil = 0x0;
    
    public static void startLocation(Context context) {
        initLocationUtil(context);
    }
    
    public static void stopLocation(Context context) {
        if(locationUtil != null) {
            locationUtil.stopLocation();
        }
    }
    
    public static void initLocationUtil(Context context) {
        locationUtil = MCLocationUtil.getInstance(context);
        locationUtil.requestLocation(new MCLocationUtil.LocationDelegate(context) {
            
            public void onReceiveLocation(BDLocation location) {
                if(location != null) {
                    SharedPreferencesDB.getInstance(context.getApplicationContext()).saveLocation(location);
                    new Thread(this, location) {
                        
                        public void run() {
                            new LocationServiceImpl(val$context).saveLocation(location.getLongitude(), location.getLatitude(), location.getAddrStr());
                        }
                    }.start();
                }
            }
        });
    }
}
