/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.helper;

import java.io.File;
import android.content.Context;
import com.mobcent.lowest.base.utils.MCResource;
import android.content.res.Resources;
import com.mobcent.lowest.base.utils.MCLibIOUtil;
import com.mobcent.discuz.android.db.SharedPreferencesDB;
import com.mobcent.android.model.MCShareModel;
import com.mobcent.share.android.helper.MCShareHelper;
import com.mobcent.share.android.helper.MCShareTCHelper;

public class MCForumLaunchShareHelper {
    public static final String LOCAL_POSITION_DIR = File.separator + "mobcent" + File.separator + "share" + File.separator;
    
    public static void share(Context context, MCShareModel shareModel) {
        shareModel.setDownloadUrl(getShareDownURL(shareModel.getDownloadUrl(), context));
        shareModel.setAppKey(getShareAppKey(context));
        MCShareHelper.share(context, shareModel);
    }
    
    public static void shareToWeChat(Context context, MCShareModel shareModel) {
        shareModel.setDownloadUrl(getShareDownURL(shareModel.getDownloadUrl(), context));
        shareModel.setAppKey(getShareAppKey(context));
        MCShareHelper.shareToWeChat(context, shareModel);
        MCShareTCHelper.share(context, 0x1, shareModel.getTitle());
    }
    
    public static void shareToMoments(Context context, MCShareModel shareModel) {
        shareModel.setDownloadUrl(getShareDownURL(shareModel.getDownloadUrl(), context));
        shareModel.setAppKey(getShareAppKey(context));
        MCShareHelper.shareToMoments(context, shareModel);
        MCShareTCHelper.share(context, 0x2, shareModel.getTitle());
    }
    
    private static String getImageSharePath(Context context) {
        return MCLibIOUtil.getBaseLocalLocation(context) + LOCAL_POSITION_DIR + "mcshareimage.jpg";
    }
    
    public static String getDefaultShareUrl(Context context) {
        int shareUrlResId = MCResource.getInstance(context).getStringId("mc_forum_share_url");
        if(shareUrlResId <= 0) {
            return "";
        }
        return getResources().getString(shareUrlResId);
    }
    
    public static String getShareDownURL(String shareURL, Context context) {
        // :( Parsing error. Please contact me.
    }
    
    public static String getShareAppKey(Context context) {
        String appkey = "";
        try {
            return appkey;
        } catch(Exception e) {
            return appkey;
        }
        return appkey;
    }
}
