/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.helper;

import com.mobcent.discuz.base.widget.TopBarWidget;
import com.mobcent.discuz.base.model.TopSettingModel;
import android.view.View;

public class TopBarHelper {
    private TopBarWidget topBox;
    
    public void dealTopBar(TopSettingModel topSettingModel) {
        if(topBox != null) {
            topBox.resetTopSetting(topSettingModel);
        }
    }
    
    public void changeTitle(String title) {
        if(topBox != null) {
            topBox.changeTitle(title);
        }
    }
    
    public void registerClickListener(View.OnClickListener onClickListener) {
        if(topBox != null) {
            topBox.registerClickListener(onClickListener);
        }
    }
    
    public TopBarWidget getTopBox() {
        return topBox;
    }
    
    public void setTopBox(TopBarWidget topBox) {
        topBox = topBox;
    }
    
    public void hideTopBar() {
        if(topBox != null) {
            topBox.setVisibility(0x8);
        }
    }
    
    public void showTopBar() {
        if(topBox != null) {
            topBox.setVisibility(0x0);
        }
    }
}
