/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.mobcent.discuz.base.helper;


public interface TopBarOptImpl {
    
    public abstract TopBarHelper getTopBarHelper();
    
}
